image: node:latest

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - yarn install

test:
  script:
    - yarn coverage && yarn codecov
  except:
    - tags
